[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
restartPolicyType = "on_failure"
healthcheckPath = "/health"
healthcheckTimeout = 300

[service]
internal_port = "8000"

[variables]
# OpenAI API key should be set in the Railway project settings
# This is just a placeholder
OPENAI_API_KEY = "${OPENAI_API_KEY}"
